export const cardData = [
    {
      avatarLetter: "ZR",
      upperTitle: "React-Redux",
      upperDate: "Sep 17, 2021",
      title: "REACT-REDUX",
      shortContent: "Redux is a predictable state container designed to help you write JavaScript apps that behave consistently across client, server, and native environments and are easy to test. While it's mostly used as a state management tool with React, you can use it with any other JavaScript framework or library.",
      name:"Zara Ratop",
      lowerDate: "Sep 17, 2021",
      dropdownTitle: "Continue reading",
      p1:"test1 test1",
      p2:"test2 test1",
      p3:"test3 test1",
      p4:"test4 test1",
      imageUrl:"https://images.pexels.com/photos/2004161/pexels-photo-2004161.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
      avatarUrl:"https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",

    },
    {
      avatarLetter: "KL",
      upperTitle: "React-Styling",
      upperDate: "Sep 17, 2021",
      title: "REACT-STYLING",
      shortContent: "Styled-Components  state container designed to help you write JavaScript apps that behave consistently across client, server, and native environments and are easy to test. While it's mostly used as a state management tool with React, you can use it with any other JavaScript framework or library.",
      name:"Kenn Lado",
      lowerDate: "Sep 17, 2021",
      dropdownTitle: "Continue reading",
      p1:"test3 test1",
      p2:"test4 test1",
      p3:"test5 test1",
      p4:"test6 test1",
      imageUrl:"https://images.pexels.com/photos/1438082/pexels-photo-1438082.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
      avatarUrl:"https://images.pexels.com/photos/6652928/pexels-photo-6652928.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",

      
    },
      {
        avatarLetter: "DW",
        upperTitle: "React-context",
        upperDate: "Sep 17, 2021",
        title: "REACT-REDUX",
        shortContent: "Redux is a predictable state container designed to help you write JavaScript apps that behave consistently across client, server, and native environments and are easy to test. While it's mostly used as a state management tool with React, you can use it with any other JavaScript framework or library.",
        name:"Dwain Wood",
        lowerDate: "Sep 17, 2021",
        dropdownTitle: "Continue reading",
        p1:"test1 test1",
        p2:"test2 test1",
        p3:"test3 test1",
        p4:"test4 test1",
        imageUrl:"https://images.pexels.com/photos/1714208/pexels-photo-1714208.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
      avatarUrl:"https://images.pexels.com/photos/5384429/pexels-photo-5384429.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",

      },

      {
          avatarLetter: "JY",
          upperTitle: "React-Hooks",
          upperDate: "Sep 17, 2021",
          title: "REACT-REDUX",
          shortContent: "Redux is a predictable state container designed to help you write JavaScript apps that behave consistently across client, server, and native environments and are easy to test. While it's mostly used as a state management tool with React, you can use it with any other JavaScript framework or library.",
          name:"Julia Yenn",
          lowerDate: "Sep 17, 2021",
          dropdownTitle: "Continue reading",
          p1:"test1 test1",
          p2:"test2 test1",
          p3:"test3 test1",
          p4:"test4 test1",
          imageUrl:"https://images.pexels.com/photos/4260477/pexels-photo-4260477.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
          avatarUrl:"https://images.pexels.com/photos/3671083/pexels-photo-3671083.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        },

        {
          avatarLetter: "JY",
          upperTitle: "React-Hooks",
          upperDate: "Sep 17, 2021",
          title: "REACT-REDUX",
          shortContent: "Redux is a predictable state container designed to help you write JavaScript apps that behave consistently across client, server, and native environments and are easy to test. While it's mostly used as a state management tool with React, you can use it with any other JavaScript framework or library.",
          name:"Julia Yenn",
          lowerDate: "Sep 17, 2021",
          dropdownTitle: "Continue reading",
          p1:"test1 test1",
          p2:"test2 test1",
          p3:"test3 test1",
          p4:"test4 test1",
          imageUrl:"https://images.pexels.com/photos/4260477/pexels-photo-4260477.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
          avatarUrl:"https://images.pexels.com/photos/3671083/pexels-photo-3671083.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        },
        {
          avatarLetter: "JY",
          upperTitle: "React-Hooks",
          upperDate: "Sep 17, 2021",
          title: "REACT-REDUX",
          shortContent: "Redux is a predictable state container designed to help you write JavaScript apps that behave consistently across client, server, and native environments and are easy to test. While it's mostly used as a state management tool with React, you can use it with any other JavaScript framework or library.",
          name:"Julia Yenn",
          lowerDate: "Sep 17, 2021",
          dropdownTitle: "Continue reading",
          p1:"test1 test1",
          p2:"test2 test1",
          p3:"test3 test1",
          p4:"test4 test1",
          imageUrl:"https://images.pexels.com/photos/4260477/pexels-photo-4260477.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
          avatarUrl:"https://images.pexels.com/photos/3671083/pexels-photo-3671083.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        },
        {
          avatarLetter: "JY",
          upperTitle: "React-Hooks",
          upperDate: "Sep 17, 2021",
          title: "REACT-REDUX",
          shortContent: "Redux is a predictable state container designed to help you write JavaScript apps that behave consistently across client, server, and native environments and are easy to test. While it's mostly used as a state management tool with React, you can use it with any other JavaScript framework or library.",
          name:"Julia Yenn",
          lowerDate: "Sep 17, 2021",
          dropdownTitle: "Continue reading",
          p1:"test1 test1",
          p2:"test2 test1",
          p3:"test3 test1",
          p4:"test4 test1",
          imageUrl:"https://images.pexels.com/photos/4260477/pexels-photo-4260477.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
          avatarUrl:"https://images.pexels.com/photos/3671083/pexels-photo-3671083.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        },
  
      
  ];